# GENERATED by sio_core.authz.rego_from_policy — do not edit.
#
# Regenerate with: just policies
#
# Hand-editing this file would recreate the exact problem it exists to prevent: two
# implementations of one policy, drifting, until dev allows what production denies.
# Generated 2026-07-25 from 29 rules.

package sio.authz

import rego.v1

default allow := false

# An authenticated principal is one with a tenant.
authenticated if input.principal.tenant != ""

# Admin bypass, except where a rule demands the pii_scope claim.
#
# tenant_matches is asserted HERE, not only in the per-rule blocks below. Omitting it let an
# admin read another tenant's data — which is exactly what the Python engine did on its first
# run, before the check was moved above the bypass. An admin is an admin OF A TENANT; there is
# deliberately no cross-tenant role in this model.
allow if {
	authenticated
	"admin" in input.principal.roles
	not pii_rule_applies
	known_action
	tenant_matches
}

# An action the policy defines. The admin bypass applies only to these.
known_action if startswith(input.action, "admin.")
known_action if input.action == "policy.write"
known_action if input.action == "tenant.create"
known_action if input.action == "decision.approve"
known_action if input.action == "decision.reject"
known_action if input.action == "workflow.execute"
known_action if input.action == "simulation.inject"
known_action if input.action == "simulation.write"
known_action if input.action == "pii.view"
known_action if input.action == "media.raw"
known_action if input.action == "media.read"
known_action if input.action == "alerts.write"
known_action if input.action == "decisions.write"
known_action if input.action == "agents.write"
known_action if input.action == "workflow.write"
known_action if input.action == "timeline.write"
known_action if input.action == "forecasts.write"
known_action if input.action == "events.write"
known_action if input.action == "analytics.read"
known_action if input.action == "model.read"
known_action if input.action == "entities.read"
known_action if input.action == "events.read"
known_action if input.action == "alerts.read"
known_action if input.action == "copilot.ask"
known_action if startswith(input.action, "graphql.")
known_action if input.action == "integration.write"
known_action if input.action == "integration.read"
known_action if input.action == "model.write"
known_action if endswith(input.action, ".read")

pii_rule_applies if {
	input.action in ["pii.view", "media.raw"]
}

# Administrative surfaces are admin-only
allow if {
	authenticated
	startswith(input.action, "admin.")
	some role in ["admin"]
	role in input.principal.roles
	tenant_matches
}

# Editing policy needs admin and high clearance: it is the lock on every other door
allow if {
	authenticated
	input.action == "policy.write"
	not startswith(input.action, "admin.")
	some role in ["admin"]
	role in input.principal.roles
	input.principal.clearance >= 3
	tenant_matches
}

# Creating tenants is administrative
allow if {
	authenticated
	input.action == "tenant.create"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	some role in ["admin"]
	role in input.principal.roles
	tenant_matches
}

# Authorising an action in the physical world is a commander's decision
allow if {
	authenticated
	input.action == "decision.approve"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	some role in ["commander", "admin"]
	role in input.principal.roles
	input.principal.clearance >= 2
	tenant_matches
}

# Rejecting is safe: it results in nothing happening
allow if {
	authenticated
	input.action == "decision.reject"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	some role in ["operator", "commander", "admin"]
	role in input.principal.roles
	tenant_matches
}

# Running a playbook can dispatch responders
allow if {
	authenticated
	input.action == "workflow.execute"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	some role in ["commander", "admin"]
	role in input.principal.roles
	input.principal.clearance >= 2
	tenant_matches
}

# Injecting a simulated incident affects no physical thing
allow if {
	authenticated
	input.action == "simulation.inject"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	some role in ["operator", "commander", "admin", "ml_engineer"]
	role in input.principal.roles
	tenant_matches
}

# Running a what-if projection; it reads a frozen copy of the world and changes nothing
allow if {
	authenticated
	input.action == "simulation.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	some role in ["viewer", "operator", "commander", "admin", "ml_engineer", "integrator", "service"]
	role in input.principal.roles
	tenant_matches
}

# Unredacted personal data needs both the role and the explicit scope
allow if {
	authenticated
	input.action == "pii.view"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	some role in ["commander", "admin"]
	role in input.principal.roles
	input.principal.clearance >= 2
	input.principal.pii_scope == true
	tenant_matches
}

# Unblurred frames contain faces and plates
allow if {
	authenticated
	input.action == "media.raw"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	some role in ["commander", "admin"]
	role in input.principal.roles
	input.principal.pii_scope == true
	tenant_matches
}

# Stored frames, which are blurred before they reach the object store. The unblurred originals are a different action (media.raw) behind a different door
allow if {
	authenticated
	input.action == "media.read"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	zone_permitted
	tenant_matches
}

# Acknowledging and resolving is an operator's job
allow if {
	authenticated
	input.action == "alerts.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	some role in ["operator", "commander", "admin"]
	role in input.principal.roles
	tenant_matches
}

# Asking for a recommendation. Producing options is not acting on them
allow if {
	authenticated
	input.action == "decisions.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	some role in ["service", "operator", "commander", "admin"]
	role in input.principal.roles
	tenant_matches
}

# An agent recording its own observations and proposals
allow if {
	authenticated
	input.action == "agents.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	some role in ["service", "admin"]
	role in input.principal.roles
	tenant_matches
}

# Recording playbook progress; executing is workflow.execute and needs a commander
allow if {
	authenticated
	input.action == "workflow.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	some role in ["service", "commander", "admin"]
	role in input.principal.roles
	tenant_matches
}

# Starting and cancelling a replay session; it reconstructs history, it changes none
allow if {
	authenticated
	input.action == "timeline.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	some role in ["operator", "commander", "admin", "ml_engineer", "integrator", "service"]
	role in input.principal.roles
	tenant_matches
}

# Running a forecast on demand
allow if {
	authenticated
	input.action == "forecasts.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	some role in ["operator", "commander", "admin", "ml_engineer", "service"]
	role in input.principal.roles
	tenant_matches
}

# Reloading rules and simulating an event for testing
allow if {
	authenticated
	input.action == "events.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	some role in ["operator", "commander", "admin", "ml_engineer", "service"]
	role in input.principal.roles
	tenant_matches
}

# Aggregate KPIs, heatmaps and reports; individual positions are suppressed server-side
allow if {
	authenticated
	input.action == "analytics.read"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	zone_permitted
	tenant_matches
}

# Which detector, tracker and thresholds are running — diagnostic, and useful to all
allow if {
	authenticated
	input.action == "model.read"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	tenant_matches
}

# Anyone authenticated may read entities, within their permitted zones
allow if {
	authenticated
	input.action == "entities.read"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	zone_permitted
	tenant_matches
}

# Reading events, within permitted zones
allow if {
	authenticated
	input.action == "events.read"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	zone_permitted
	tenant_matches
}

# Reading alerts, within permitted zones
allow if {
	authenticated
	input.action == "alerts.read"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	input.action != "events.read"
	zone_permitted
	tenant_matches
}

# Asking questions; the answers are redacted unless pii.view also passes
allow if {
	authenticated
	input.action == "copilot.ask"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	input.action != "events.read"
	input.action != "alerts.read"
	some role in ["operator", "commander", "admin", "ml_engineer", "integrator", "service"]
	role in input.principal.roles
	tenant_matches
}

# GraphQL queries over the world model; read parity with the REST surface
allow if {
	authenticated
	startswith(input.action, "graphql.")
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	input.action != "events.read"
	input.action != "alerts.read"
	input.action != "copilot.ask"
	some role in ["operator", "commander", "admin", "ml_engineer", "integrator", "service"]
	role in input.principal.roles
	tenant_matches
}

# Registering connectors and webhooks. Narrow on purpose: creating a webhook points this platform's data at an external URL, which is a data-egress decision rather than an operational one
allow if {
	authenticated
	input.action == "integration.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	input.action != "events.read"
	input.action != "alerts.read"
	input.action != "copilot.ask"
	not startswith(input.action, "graphql.")
	some role in ["integrator", "admin"]
	role in input.principal.roles
	tenant_matches
}

# Reading webhook subscriptions and their delivery log. A commander may look, because 'did the notification go out?' is an operational question during an incident
allow if {
	authenticated
	input.action == "integration.read"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	input.action != "events.read"
	input.action != "alerts.read"
	input.action != "copilot.ask"
	not startswith(input.action, "graphql.")
	input.action != "integration.write"
	some role in ["integrator", "admin", "commander"]
	role in input.principal.roles
	tenant_matches
}

# Changing models and thresholds
allow if {
	authenticated
	input.action == "model.write"
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	input.action != "events.read"
	input.action != "alerts.read"
	input.action != "copilot.ask"
	not startswith(input.action, "graphql.")
	input.action != "integration.write"
	input.action != "integration.read"
	some role in ["ml_engineer", "admin"]
	role in input.principal.roles
	tenant_matches
}

# Any authenticated principal may read, unless a narrower rule said otherwise
allow if {
	authenticated
	endswith(input.action, ".read")
	not startswith(input.action, "admin.")
	input.action != "policy.write"
	input.action != "tenant.create"
	input.action != "decision.approve"
	input.action != "decision.reject"
	input.action != "workflow.execute"
	input.action != "simulation.inject"
	input.action != "simulation.write"
	input.action != "pii.view"
	input.action != "media.raw"
	input.action != "media.read"
	input.action != "alerts.write"
	input.action != "decisions.write"
	input.action != "agents.write"
	input.action != "workflow.write"
	input.action != "timeline.write"
	input.action != "forecasts.write"
	input.action != "events.write"
	input.action != "analytics.read"
	input.action != "model.read"
	input.action != "entities.read"
	input.action != "events.read"
	input.action != "alerts.read"
	input.action != "copilot.ask"
	not startswith(input.action, "graphql.")
	input.action != "integration.write"
	input.action != "integration.read"
	input.action != "model.write"
	tenant_matches
}

# An empty zone list is UNRESTRICTED, not 'no zones'. Inverting this would lock out every
# ordinary operator while looking like a tightening.
zone_permitted if count(input.principal.zones) == 0
zone_permitted if not input.context.zone_id
zone_permitted if input.context.zone_id in input.principal.zones

tenant_matches if not input.context.tenant_id
tenant_matches if input.context.tenant_id == input.principal.tenant
