"""Turning a solved plan into ranked options a human can choose between (PRD M12).

The acceptance criterion is that **every recommendation shows ranked options, expected effect, and a
rationale.** That rules out returning the optimum: an objective function encodes somebody's opinion about
trade-offs, and presenting only the winner hides both the runner-up and the fact that a choice was made.

So options are generated by solving the *same problem under different objectives* — send the nearest, send
the best-suited, send nobody — and each is costed with the same measurements. An operator can then see that
option two arrives ninety seconds later with a responder twice as suitable, and decide. That is a different
activity from being told.

**The alternatives are real solves, not perturbations of the winner.** Ranking the optimum and then
inventing plausible-sounding runners-up would produce numbers that do not correspond to anything, which is
worse than showing one option, because the numbers would look checkable.

The rationale prefers an LLM and falls back to a template. The template is not a degraded mode — it is
built from the same measurements and is arguably more trustworthy, so the fallback is labelled rather than
apologised for.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from sio_core import get_logger
from sio_core.explain import ExplanationBuilder
from sio_schemas import (
    ActionType,
    Decision,
    DecisionOption,
    Explanation,
    Severity,
    utc_now,
)

from .solvers import (
    Incident,
    Responder,
    SolverResult,
    haversine_m,
    solve_assignment,
    suitability,
)

log = get_logger("sio.decision.recommend")


@dataclass
class Strategy:
    """One way of deciding, with a name an operator would recognise."""

    key: str
    label: str
    description: str


STRATEGIES = (
    Strategy(
        key="balanced",
        label="Balanced",
        description="Weighs how well each responder fits the incident against how long it will take.",
    ),
    Strategy(
        key="fastest",
        label="Fastest response",
        description="Sends whoever arrives soonest, whatever they are.",
    ),
    Strategy(
        key="best_suited",
        label="Best suited",
        description="Sends the most capable responder even if it is further away.",
    ),
)


def _solve_with(
    strategy: str, responders: list[Responder], incidents: list[Incident]
) -> SolverResult:
    """Solve the same problem with a different emphasis.

    Implemented by adjusting the inputs the objective reads rather than by rewriting the model: for
    "fastest", suitability is flattened so only travel separates candidates; for "best suited", speeds are
    equalised so only fit does. Same solver, same constraints, honestly different objectives.
    """
    if strategy == "fastest":
        flattened = [
            Incident(
                incident_id=incident.incident_id,
                kind=incident.kind,
                lat=incident.lat,
                lon=incident.lon,
                severity=incident.severity,
                zone_id=incident.zone_id,
                # Requirements are kept: "fastest" must not mean "send a forklift to a fire".
                requires=incident.requires,
            )
            for incident in incidents
        ]
        # Equal suitability, so the travel penalty decides. Achieved by making every incident the same
        # generic kind, which the suitability table scores uniformly.
        flattened = [
            Incident(
                incident_id=i.incident_id,
                kind="generic",
                lat=i.lat,
                lon=i.lon,
                severity=i.severity,
                zone_id=i.zone_id,
                requires=i.requires,
            )
            for i in flattened
        ]
        return solve_assignment(responders, flattened)

    if strategy == "best_suited":
        # Equal speed, so travel time no longer separates candidates and fit decides.
        equalised = [
            Responder(
                entity_id=r.entity_id,
                kind=r.kind,
                lat=r.lat,
                lon=r.lon,
                speed_mps=1000.0,
                label=r.label,
                busy=r.busy,
                battery_pct=r.battery_pct,
                capacity=r.capacity,
            )
            for r in responders
        ]
        return solve_assignment(equalised, incidents)

    return solve_assignment(responders, incidents)


def _restore(
    result: SolverResult, responders: list[Responder], incidents: list[Incident]
) -> SolverResult:
    """Recompute the reported metrics from the REAL inputs.

    Essential, and easy to get wrong. The "best suited" solve equalises speeds to change what the objective
    optimises — if its ETAs were reported as solved, the option would claim a 3-second response from a
    responder that will actually take four minutes. The plan comes from the modified solve; the numbers
    shown come from reality.
    """
    by_id = {responder.entity_id: responder for responder in responders}
    incidents_by_id = {incident.incident_id: incident for incident in incidents}
    for assignment in result.assignments:
        real_responder = by_id.get(assignment.responder.entity_id, assignment.responder)
        real_incident = incidents_by_id.get(assignment.incident.incident_id, assignment.incident)
        assignment.responder = real_responder
        assignment.incident = real_incident
        assignment.distance_m = haversine_m(
            real_responder.lat, real_responder.lon, real_incident.lat, real_incident.lon
        )
        assignment.eta_s = assignment.distance_m / max(0.5, real_responder.speed_mps)
        assignment.suitability = suitability(real_responder, real_incident)
    result.total_distance_m = sum(a.distance_m for a in result.assignments)
    return result


def build_options(
    responders: list[Responder], incidents: list[Incident]
) -> tuple[list[DecisionOption], dict[str, SolverResult]]:
    """Generate ranked options by solving under each strategy, plus the do-nothing option."""
    options: list[DecisionOption] = []
    solves: dict[str, SolverResult] = {}

    for strategy in STRATEGIES:
        result = _restore(_solve_with(strategy.key, responders, incidents), responders, incidents)
        solves[strategy.key] = result
        if not result.ok or not result.assignments:
            options.append(
                DecisionOption(
                    action=ActionType.NO_ACTION,
                    score=0.0,
                    expected_effect=f"{strategy.label}: no viable assignment",
                    feasible=False,
                    rejection_reason=(
                        "; ".join(result.notes) or f"the solver returned {result.status}"
                    ),
                    params={"strategy": strategy.key},
                )
            )
            continue

        first = result.assignments[0]
        # The score is comparable across strategies because it is recomputed from the real metrics, not
        # taken from each solve's own objective — those objectives are in different units by construction.
        score = sum(
            assignment.incident.weight * assignment.suitability - assignment.eta_s / 60
            for assignment in result.assignments
        )
        options.append(
            DecisionOption(
                action=_action_for(first.responder.kind),
                target_entity_id=first.responder.entity_id,
                score=round(score, 3),
                expected_effect=_effect_sentence(strategy, result),
                expected_metrics={
                    "assignments": float(len(result.assignments)),
                    "unassigned": float(len(result.unassigned)),
                    "first_eta_s": round(first.eta_s, 1),
                    "worst_eta_s": round(result.worst_eta_s, 1),
                    "total_distance_m": round(result.total_distance_m, 1),
                    "mean_suitability": round(
                        sum(a.suitability for a in result.assignments) / len(result.assignments), 3
                    ),
                },
                cost=round(result.total_distance_m / 1000, 3),
                risk=round(min(1.0, len(result.unassigned) / max(1, len(incidents))), 3),
                params={
                    "strategy": strategy.key,
                    "plan": [assignment.describe() for assignment in result.assignments],
                },
            )
        )

    # Do nothing, always costed and always shown.
    #
    # Not a formality. For a low-severity incident with only a low-battery drone available, waiting IS the
    # right answer, and an options list that never contains it teaches an operator that the system always
    # wants to act.
    worst_severity = max((incident.weight for incident in incidents), default=0.0)
    options.append(
        DecisionOption(
            action=ActionType.NO_ACTION,
            score=round(-worst_severity, 3),
            expected_effect=(
                f"Nothing is dispatched. {len(incidents)} incident(s) remain unattended, the most severe "
                f"being {max(incidents, key=lambda i: i.weight).severity if incidents else 'none'}."
            ),
            expected_metrics={"unassigned": float(len(incidents)), "first_eta_s": 0.0},
            cost=0.0,
            risk=1.0 if incidents else 0.0,
            params={"strategy": "do_nothing"},
        )
    )

    options = _merge_agreeing(options)
    options.sort(key=lambda option: (-option.score, option.cost))
    return options, solves


def _merge_agreeing(options: list[DecisionOption]) -> list[DecisionOption]:
    """Collapse options whose plans are identical, recording which strategies agreed.

    Measured on a real scenario: with three responders and two incidents, all three strategies chose the
    same assignment and the options list showed the same plan three times with the same score. That is
    noise, and worse, it buries a genuinely useful fact — **when independent objectives agree, the
    recommendation is stronger than any one of them.** Merging surfaces that instead of repeating it.

    Options are compared on the PLAN (who goes where), not on the score. Two strategies that reach the same
    assignment by different routes have still agreed about what to do, which is the only part an operator
    acts on.
    """
    merged: dict[str, DecisionOption] = {}
    order: list[str] = []
    for option in options:
        plan = option.params.get("plan") or []
        signature = (
            "|".join(f"{entry.get('responder')}->{entry.get('incident')}" for entry in plan)
            or f"none:{option.params.get('strategy')}"
        )
        existing = merged.get(signature)
        if existing is None:
            option.params["strategies"] = [option.params.get("strategy")]
            merged[signature] = option
            order.append(signature)
            continue
        existing.params["strategies"].append(option.params.get("strategy"))

    for signature in order:
        option = merged[signature]
        agreed = [name for name in option.params.get("strategies", []) if name]
        if len(agreed) > 1:
            labels = {strategy.key: strategy.label for strategy in STRATEGIES}
            names = ", ".join(labels.get(name, name) for name in agreed)
            # Stated in the effect, because it is the part that should change an operator's confidence.
            option.expected_effect = (
                f"{option.expected_effect} — all of {names} chose this plan independently"
            )
            option.params["strategy"] = "+".join(agreed)
    return [merged[signature] for signature in order]


def _action_for(kind: str) -> ActionType:
    return {
        "drone": ActionType.DISPATCH_DRONE,
        "patrol": ActionType.DISPATCH_PATROL,
        "ambulance": ActionType.DEPLOY_AMBULANCE,
    }.get(kind, ActionType.DISPATCH_PATROL)


def _effect_sentence(strategy: Strategy, result: SolverResult) -> str:
    """A plain-language effect with the numbers in it.

    "Contains the fire" is a claim this system cannot support. "Drone 0018 reaches dock_3 in about 40
    seconds" is a measurement, and it is what the schema's `expected_effect` should carry.
    """
    first = result.assignments[0]
    parts = [
        f"{strategy.label}: {first.responder.name} reaches {first.incident.incident_id} in about "
        f"{first.eta_s:.0f}s ({first.distance_m:.0f} m away, suitability {first.suitability:.0%})"
    ]
    if len(result.assignments) > 1:
        parts.append(
            f"{len(result.assignments)} responders dispatched, slowest arriving in "
            f"{result.worst_eta_s:.0f}s"
        )
    if result.unassigned:
        parts.append(f"{len(result.unassigned)} incident(s) left unattended")
    return "; ".join(parts)


def template_rationale(options: list[DecisionOption], incidents: list[Incident]) -> str:
    """A rationale built from the numbers, used when no model is available.

    Not a degraded mode. It is assembled from the same measurements the options were scored on, and is
    arguably more trustworthy than a generated paragraph — so it is labelled rather than apologised for.
    """
    if not options:
        return "There are no options to compare."
    best = options[0]
    runner_up = next(
        (
            option
            for option in options[1:]
            if option.feasible and option.action != ActionType.NO_ACTION
        ),
        None,
    )
    lines = [
        f"Recommending {best.action} "
        f"({best.params.get('strategy', 'balanced')}): {best.expected_effect}."
    ]
    if runner_up is not None:
        difference = best.score - runner_up.score
        lines.append(
            f"The next best option scores {difference:.1f} lower "
            f"({runner_up.params.get('strategy')}): {runner_up.expected_effect}."
        )
    if incidents:
        worst = max(incidents, key=lambda incident: incident.weight)
        lines.append(
            f"The most severe incident is {worst.incident_id} ({worst.severity}) in "
            f"{worst.zone_id or 'the yard'}."
        )
    unattended = best.expected_metrics.get("unassigned", 0)
    if unattended:
        lines.append(
            f"{unattended:.0f} incident(s) would remain unattended under this option, which is why doing "
            "nothing is also listed."
        )
    return " ".join(lines)


async def llm_rationale(
    llm: Any, options: list[DecisionOption], incidents: list[Incident]
) -> tuple[str, str | None]:
    """Ask a model to explain the ranking in prose. Returns (text, degraded reason).

    The model is given the numbers and asked to explain, never to decide. A model that could change the
    ranking would make the optimiser decorative, and the optimiser is the part that can be checked.
    """
    if llm is None:
        return template_rationale(options, incidents), "no model configured; using the template"

    summary = "\n".join(
        f"- {option.params.get('strategy', '?')}: score {option.score:.1f}, "
        f"cost {option.cost:.2f} km, risk {option.risk:.2f} — {option.expected_effect}"
        for option in options[:4]
    )
    prompt = (
        "You are explaining an automated recommendation to a yard operator.\n\n"
        f"Options, already ranked by the optimiser:\n{summary}\n\n"
        "In two or three sentences: say which option is recommended and why, and name the main trade-off "
        "against the runner-up. Quote the actual numbers. Do not change the ranking, and do not invent "
        "anything that is not above."
    )
    try:
        reply = await llm.chat(
            [{"role": "user", "content": prompt}], temperature=0.2, max_tokens=200
        )
    except Exception as exc:
        log.warning("decision.rationale_failed", error=str(exc))
        return template_rationale(
            options, incidents
        ), f"the model failed ({exc}); using the template"

    if not reply.text.strip():
        return template_rationale(
            options, incidents
        ), "the model returned nothing; using the template"
    return reply.text.strip(), reply.degraded


def build_decision(
    *,
    tenant_id: str,
    options: list[DecisionOption],
    solves: dict[str, SolverResult],
    incidents: list[Incident],
    responders: list[Responder],
    rationale: str,
    degraded: str | None,
    trigger_event: str | None = None,
    proposed_by: str = "decision",
) -> Decision:
    """Assemble the Decision, including the explanation that makes the ranking inspectable."""
    best = options[0] if options else None
    builder = ExplanationBuilder(
        summary=(best.expected_effect if best else "No options could be generated")
    )
    builder.add_model(
        "ortools-cpsat", note="assignment solved under three objectives plus do-nothing"
    )
    builder.add_note(f"{len(responders)} responder(s) and {len(incidents)} incident(s) considered")
    for option in options:
        builder.add_note(
            f"option {option.params.get('strategy', '?')}: score {option.score:.1f}, "
            f"cost {option.cost:.2f} km, risk {option.risk:.2f}"
            + (f" — REJECTED: {option.rejection_reason}" if not option.feasible else "")
        )
        # Every option becomes an alternative in the explanation, so the drawer shows what was NOT chosen
        # and why — which is the part that makes a ranking reviewable rather than merely presented.
        if best is not None and option.option_id != best.option_id:
            builder.add_alternative(
                option.expected_effect,
                confidence=max(0.0, min(1.0, option.score / max(1.0, abs(best.score) or 1.0))),
                why_not=(
                    option.rejection_reason
                    or f"scored {best.score - option.score:.1f} lower than the recommendation"
                ),
            )
    for key, result in solves.items():
        builder.add_note(
            f"{key} solve: {result.status} in {result.solve_ms:.0f} ms, "
            f"{len(result.assignments)} assignment(s)"
        )
    if degraded:
        builder.add_note(f"rationale: {degraded}")
    builder.confidence(0.8 if best and best.feasible else 0.3)

    return Decision(
        tenant_id=tenant_id,
        trigger_event=trigger_event,
        ts=utc_now(),
        options=options,
        chosen=best.option_id if best else None,
        rationale=rationale,
        expected_effect=best.expected_effect if best else "",
        confidence=0.8 if best and best.feasible else 0.3,
        explanation=builder.build(),
        proposed_by=proposed_by,
        solver="ortools-cpsat",
    )


def severity_of(value: Any) -> str:
    try:
        return str(Severity(value))
    except ValueError:
        return "high"


__all__ = [
    "STRATEGIES",
    "Explanation",
    "build_decision",
    "build_options",
    "llm_rationale",
    "template_rationale",
]
