import { useEffect, useState } from "react";
import { api, explainError } from "../lib/api";
import { protectedBlob } from "../lib/review-api";
import * as session from "../lib/session";
import { poseFields, setupBody, setupDraft, type CameraSetupRecord, type CheckpointDraft, type SetupDraft, type SetupSite, type SetupSource } from "../lib/commissioning";
import "./review.css";
import "./commissioning.css";

type Context = { sites: SetupSite[]; sources: SetupSource[]; sources_available: boolean; source_error?: string };
type Preview = { available: boolean; reason?: string; media_url?: string; ts?: string; width?: number; height?: number };

export function CameraSetupPanel({initialSiteId, initialSourceId, onOpenSite}: {initialSiteId?: string; initialSourceId?: string; onOpenSite?: (id: string) => void}) {
  const [context, setContext] = useState<Context>({sites: [], sources: [], sources_available: true});
  const [setups, setSetups] = useState<CameraSetupRecord[]>([]);
  const [selected, setSelected] = useState<CameraSetupRecord | null>(null);
  const [draft, setDraft] = useState<SetupDraft>(setupDraft());
  const [step, setStep] = useState(1);
  const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState("");
  const [preview, setPreview] = useState<Preview | null>(null);
  const [image, setImage] = useState<string | null>(null);
  const [previewVersion, setPreviewVersion] = useState(0);
  const canEdit = session.can("site.write");
  const source = context.sources.find(row => row.source_id === draft.source_id);
  const site = context.sites.find(row => row.site_id === draft.site_id);
  const camera = site?.cameras.find(row => row.camera_id === draft.camera_id);

  useEffect(() => {
    const controller = new AbortController(); setLoading(true);
    void Promise.all([api.request<Context>("/camera-setups/context", {signal: controller.signal}), api.request<{setups: CameraSetupRecord[]}>("/camera-setups", {signal: controller.signal})]).then(([value, saved]) => {
      if (controller.signal.aborted) return;
      setContext(value); setSetups(saved.setups);
      const first = saved.setups.find(row => (!initialSiteId || row.site_id === initialSiteId) && (!initialSourceId || row.source_id === initialSourceId));
      setSelected(first ?? null); setDraft(first ? setupDraft(first) : {...setupDraft(), site_id: initialSiteId ?? "", source_id: initialSourceId ?? ""}); setDirty(false);
    }).catch(cause => {if (!controller.signal.aborted) setError(explainError(cause));}).finally(() => {if (!controller.signal.aborted) setLoading(false);});
    return () => controller.abort();
  }, [initialSiteId, initialSourceId]);

  useEffect(() => {
    const controller = new AbortController(); let objectUrl: string | null = null; setImage(null); setPreview(null);
    if (draft.source_id && session.can("media.read")) void api.request<Preview>(`/camera-setups/sources/${encodeURIComponent(draft.source_id)}/preview`, {signal: controller.signal}).then(async value => {
      if (controller.signal.aborted) return; setPreview(value);
      if (value.available && value.media_url) { const blob = await protectedBlob(value.media_url, controller.signal, 20 * 1024 * 1024); if (controller.signal.aborted) return; objectUrl = URL.createObjectURL(blob); setImage(objectUrl); }
    }).catch(cause => {if (!controller.signal.aborted) setPreview({available: false, reason: explainError(cause)});});
    return () => {controller.abort(); if (objectUrl) URL.revokeObjectURL(objectUrl);};
  }, [draft.source_id, previewVersion]);

  function edit(changes: Partial<SetupDraft>) { setDraft(value => ({...value, ...changes})); setDirty(true); setNotice(""); }
  function choose(record: CameraSetupRecord | null) { setSelected(record); setDraft(setupDraft(record ?? undefined)); setStep(1); setDirty(false); setNotice(""); setError(null); }
  function accept(record: CameraSetupRecord) {setSelected(record); setDraft(setupDraft(record)); setSetups(rows => [record, ...rows.filter(row => row.setup_id !== record.setup_id)]); setDirty(false);}
  async function run(action: () => Promise<void>) {setBusy(true); setError(null); setNotice(""); try {await action();} catch (cause) {setError(explainError(cause));} finally {setBusy(false);}}
  async function save() {const record = await api.request<CameraSetupRecord>(selected ? `/camera-setups/${encodeURIComponent(selected.setup_id)}` : "/camera-setups", {method: selected ? "PUT" : "POST", body: JSON.stringify(setupBody(draft, selected?.revision ?? 0))}); accept(record); setNotice(`Draft saved at revision ${record.revision}. Source settings are unchanged.`);}
  function addCheckpoint(x = "", y = "") { edit({checkpoints: [...draft.checkpoints, {checkpoint_id: `cp_${crypto.randomUUID().replaceAll("-", "")}`, label: `Checkpoint ${draft.checkpoints.length + 1}`, image_x: x, image_y: y, measured_east_m: "", measured_north_m: ""}]}); }
  function changePoint(id: string, changes: Partial<CheckpointDraft>) {edit({checkpoints: draft.checkpoints.map(point => point.checkpoint_id === id ? {...point, ...changes} : point)});}
  const validation = !dirty ? selected?.validation : null;
  const readyForMeasures = Boolean(source && site && camera && draft.title.trim());
  return <div className="review-shell commissioning-shell"><aside className="review-library"><span className="rv-kicker">CAMERA READINESS</span><h2>Measure<br />before use.</h2><p className="rv-muted">Prepare an existing camera and check surveyed reference points.</p>{canEdit && <button className="rv-button" disabled={busy || dirty || loading} onClick={() => choose(null)}>New setup</button>}<div className="rv-library-head"><span>Saved setups · {setups.length}</span></div><div className="rv-library-list">{setups.map(row => <button key={row.setup_id} className={`rv-library-item ${selected?.setup_id === row.setup_id ? "is-selected" : ""}`} disabled={busy || dirty} onClick={() => choose(row)}><strong>{row.title}</strong><span>{row.status === "validated" ? "Checkpoints passed" : "Draft"} · r{row.revision}</span><small>{row.source_id}</small></button>)}</div><p className="rv-library-foot rv-small">Readiness records preserve measured inputs and their validation result. They do not activate hardware.</p></aside>
    <main className="review-main"><header className="rv-page-head"><div><span className="rv-kicker">ADMINISTRATION / CAMERA SETUP</span><h1>{selected?.title ?? "Prepare a camera"}</h1></div><span className={`rv-badge ${validation?.passed ? "rv-positive" : "rv-warning"}`}>{dirty ? "Unsaved measurements" : validation?.passed ? "Checkpoint check passed" : "Draft readiness"}</span></header>
      {error && <p className="rv-error" role="alert">{error}</p>}{notice && <p className="rv-notice" role="status">{notice}</p>}{loading && <p className="rv-muted" role="status">Loading cameras and sites…</p>}
      <nav className="commissioning-steps" aria-label="Camera setup steps">{[[1, "Choose camera"], [2, "Measured pose"], [3, "Survey checkpoints"]].map(([number, label]) => <button className={step === number ? "is-current" : ""} key={number} aria-current={step === number ? "step" : undefined} disabled={loading || (Number(number) > 1 && !readyForMeasures)} onClick={() => setStep(Number(number))}><span>0{number}</span>{label}</button>)}</nav>
      {step === 1 && <section className="rv-editor-card"><h2>Connect the setup to an existing camera.</h2><p className="rv-muted">Select a configured RTSP source and its location in the site editor.</p>{!context.sources_available && <p className="rv-error" role="alert">{context.source_error}</p>}{!loading && !context.sources.length && <div className="rv-blank"><span>NO RTSP CAMERA</span><h2>No configured camera is available.</h2><p>Add an RTSP source in Sources with its connection details. A simulator is not a physical camera.</p></div>}
        <fieldset className="rv-fieldset rv-form-grid" disabled={!canEdit || busy || loading}><label>Setup title<input value={draft.title} maxLength={160} placeholder="East gate readiness survey" onChange={event => edit({title: event.target.value})} /></label><label>RTSP source<select value={draft.source_id} onChange={event => edit({source_id: event.target.value})}><option value="">Choose configured camera</option>{context.sources.map(row => <option key={row.source_id} value={row.source_id}>{row.label || row.source_id}</option>)}</select></label><label>Site<select value={draft.site_id} onChange={event => edit({site_id: event.target.value, camera_id: "", pose: {}, checkpoints: []})}><option value="">Choose site</option>{context.sites.map(row => <option key={row.site_id} value={row.site_id}>{row.name}</option>)}</select></label><label>Camera on this site<select value={draft.camera_id} onChange={event => {const row = site?.cameras.find(item => item.camera_id === event.target.value); edit({camera_id: event.target.value, pose: Object.fromEntries(Object.entries(row?.pose ?? {}).map(([key, value]) => [key, String(value)])), checkpoints: []});}}><option value="">Choose placed camera</option>{site?.cameras.map(row => <option key={row.camera_id} value={row.camera_id}>{row.name}</option>)}</select></label></fieldset>
        {!site?.cameras.length && <p className="rv-small">Place a camera on a saved site before creating its setup.</p>}{site && onOpenSite && <button className="rv-text-button" disabled={dirty || busy} onClick={() => onOpenSite(site.site_id)}>Open site layout</button>}{camera?.source_id && camera.source_id !== draft.source_id && <p className="rv-small">This camera currently names another source. This setup records your selected association without changing the site layout.</p>}
        {source && <div className="commissioning-health"><div><strong>{source.label || source.source_id}</strong><span className="rv-badge">{source.status || "Status unknown"}</span><span className="rv-badge">{source.active ? "Active in ingestion" : "Not active"}</span>{source.restart_required && <span className="rv-badge rv-warning">Ingestion restart required</span>}</div><p className="rv-small">Last success: {source.last_success ? new Date(source.last_success).toLocaleString() : "No successful observation recorded"}</p>{source.error && <p className="rv-error">{source.error}</p>}<button className="rv-button" disabled={busy || !session.can("integration.write")} onClick={() => void run(async () => {const result = await api.request<{ok: boolean; message?: string}>(`/sources/${encodeURIComponent(source.source_id)}/test`, {method: "POST", body: "{}"}); setNotice(`${result.ok ? "Connection test passed" : "Connection test failed"}${result.message ? `: ${result.message}` : "."}`);})}>Test configured connection</button><p className="rv-small">Uses the configured source test. It does not start ingestion or store a preview frame.</p></div>}
      </section>}
      {step === 2 && <section className="rv-editor-card"><h2>Enter the measured camera pose.</h2><p className="rv-muted">Use surveyed position, mounting height, orientation and calibrated field of view. Existing site values are a draft; confirm each measurement against the installed camera.</p><fieldset className="rv-fieldset rv-form-grid" disabled={!canEdit || busy}>{poseFields.map(([key, label]) => <label key={key}>{label}<input type="number" step={key.startsWith("frame_") ? 1 : "any"} value={draft.pose[key] ?? ""} placeholder="Measured value" onChange={event => edit({pose: {...draft.pose, [key]: event.target.value}})} /></label>)}</fieldset><p className="rv-small">Projection range limits the flat-ground model. The frame dimensions must match the original camera image, even when its sanitized preview is resized.</p></section>}
      {step === 3 && <div className="commissioning-survey"><section className="rv-editor-card"><div className="rv-section-title"><div><span className="rv-kicker">SANITIZED CAMERA FRAME</span><h2>Locate surveyed checkpoints.</h2></div><button className="rv-button" disabled={busy || !draft.source_id} onClick={() => setPreviewVersion(value => value + 1)}>Refresh preview</button></div><div className="commissioning-preview">{image ? <div className="commissioning-image"><img src={image} alt="Sanitized camera preview for measured checkpoints" onClick={event => {if (!canEdit || busy || draft.checkpoints.length >= 20) return; const bounds = event.currentTarget.getBoundingClientRect(); addCheckpoint(((event.clientX - bounds.left) / bounds.width).toFixed(5), ((event.clientY - bounds.top) / bounds.height).toFixed(5));}} />{draft.checkpoints.map((point, index) => point.image_x.trim() && point.image_y.trim() && <span key={point.checkpoint_id} style={{left: `${Number(point.image_x) * 100}%`, top: `${Number(point.image_y) * 100}%`}}>{index + 1}</span>)}</div> : <p className="rv-media-placeholder">{preview?.reason ?? (draft.source_id ? "No sanitized preview loaded." : "Choose a configured camera.")}</p>}</div><p className="rv-small">{preview?.ts && `Frame ${new Date(preview.ts).toLocaleString()}. `}Click the preview to mark a point, or enter normalized image coordinates below. Surveyed east and north distances are relative to the camera's ground position, in metres; west and south are negative.</p>
        <fieldset className="rv-fieldset" disabled={!canEdit || busy}><div className="commissioning-checkpoints">{draft.checkpoints.map((point, index) => <article key={point.checkpoint_id}><div className="rv-section-title"><strong>Point {index + 1}</strong><button className="rv-button" onClick={() => edit({checkpoints: draft.checkpoints.filter(row => row.checkpoint_id !== point.checkpoint_id)})}>Remove</button></div><label>Landmark label<input value={point.label} maxLength={100} onChange={event => changePoint(point.checkpoint_id, {label: event.target.value})} /></label><div className="rv-form-grid">{([['image_x', 'Image X · 0–1'], ['image_y', 'Image Y · 0–1'], ['measured_east_m', 'Surveyed east m'], ['measured_north_m', 'Surveyed north m']] as const).map(([key, label]) => <label key={key}>{label}<input type="number" step="any" min={key.startsWith("image_") ? 0 : undefined} max={key.startsWith("image_") ? 1 : undefined} value={point[key]} onChange={event => changePoint(point.checkpoint_id, {[key]: event.target.value})} /></label>)}</div></article>)}</div><button className="rv-button" disabled={draft.checkpoints.length >= 20} onClick={() => addCheckpoint()}>Add surveyed point</button><div className="rv-form-grid commissioning-measure-note"><label>Allowed residual m<input type="number" min="0.1" max="20" step="0.1" value={draft.tolerance_m} onChange={event => edit({tolerance_m: event.target.value})} /></label><label>Survey method and date<textarea rows={3} value={draft.measurement_note} maxLength={4000} placeholder="Who measured these distances, when, with which reference and instrument?" onChange={event => edit({measurement_note: event.target.value})} /></label></div></fieldset>
      </section><aside className="rv-editor-card"><span className="rv-kicker">VALIDATION RECORD</span><h2>{validation?.passed ? "Entered checkpoints agree." : "Check the survey residuals."}</h2>{validation ? <><dl className="rv-outcome-list"><div><dt>Checkpoints</dt><dd>{validation.checkpoint_count}</dd></div><div><dt>RMSE</dt><dd>{validation.rmse_m == null ? "Unavailable" : `${validation.rmse_m.toFixed(2)} m`}</dd></div><div><dt>Maximum residual</dt><dd>{validation.max_error_m == null ? "Unavailable" : `${validation.max_error_m.toFixed(2)} m`}</dd></div></dl>{validation.checkpoints.map(point => <p className="rv-small" key={point.checkpoint_id}>{point.label}: {point.error_m == null ? "Outside model coverage" : `${point.error_m.toFixed(2)} m`} · {point.passed ? "within tolerance" : "needs review"}</p>)}{validation.problems.length > 0 && <ul className="commissioning-problems">{validation.problems.map(problem => <li key={problem}>{problem}</li>)}</ul>}<p className="rv-small">Checked {new Date(validation.validated_at).toLocaleString()}</p></> : <p className="rv-muted">Save at least three noncollinear checkpoints and a survey method, then validate. The checker compares the fixed pose with your measured points.</p>}<p className="rv-small">This checks numerical agreement with entered measurements. It does not independently verify the survey, terrain, lens distortion or live detection accuracy.</p><p className="rv-small">Passing creates a readiness note. Camera configuration and live operation remain unchanged.</p></aside></div>}
      <div className="rv-save-bar"><span>{selected ? `Revision ${selected.revision}` : "New setup"}{dirty ? " · Unsaved measurements" : " · Source settings unchanged"}</span><div className="rv-row">{step > 1 && <button className="rv-button" onClick={() => setStep(step - 1)}>Back</button>}{step < 3 && <button className="rv-button" disabled={!readyForMeasures} onClick={() => setStep(step + 1)}>Continue</button>}{canEdit && <><button className="rv-button" disabled={busy || !dirty} onClick={() => {setDraft(setupDraft(selected ?? undefined)); setDirty(false); setError(null);}}>Discard edits</button><button className="rv-button" disabled={busy || !readyForMeasures || (!dirty && Boolean(selected))} onClick={() => void run(save)}>Save draft</button><button className="rv-button rv-primary" disabled={busy || dirty || !selected} onClick={() => void run(async () => {const result = await api.request<CameraSetupRecord>(`/camera-setups/${encodeURIComponent(selected!.setup_id)}/validate`, {method: "POST", body: JSON.stringify({expected_revision: selected!.revision})}); accept(result); setStep(3); setNotice(result.validation?.passed ? "Checkpoint residuals passed. Readiness was recorded; camera operation is unchanged." : "Validation completed. Review the measurement problems before using this pose.");})}>{busy ? "Working…" : "Validate saved measurements"}</button></>}</div></div>
    </main></div>;
}
