import {useEffect,useState} from 'react';
import {explainError} from '../lib/api';
import {reviewApi} from '../lib/review-api';
import * as session from '../lib/session';
import type {ReviewVideo} from '../lib/review-types';
import {mappedTargets,presetPreviewSummary,rulePresetsApi,sourceSlots,type PresetPreview,type PresetResult,type PresetSourceSlot,type RulePreset} from '../lib/rule-presets';
import './rule-presets.css';

export interface RulePresetsPanelProps {sourceVideoId?:string;disabled?:boolean;onApplied?:(videoIds:string[])=>void|Promise<void>;onBusyChange?:(busy:boolean)=>void}
export function RulePresetsPanel({sourceVideoId,disabled=false,onApplied,onBusyChange}:RulePresetsPanelProps){
  const [videos,setVideos]=useState<ReviewVideo[]>([]),[presets,setPresets]=useState<RulePreset[]>([]),[presetId,setPresetId]=useState(''),[versionId,setVersionId]=useState('');
  const [name,setName]=useState(''),[description,setDescription]=useState(''),[slots,setSlots]=useState<PresetSourceSlot[]>([]);
  const [selected,setSelected]=useState<string[]>([]),[maps,setMaps]=useState<Record<string,Record<string,string>>>({}),[mode,setMode]=useState<'append'|'replace'>('append');
  const [preview,setPreview]=useState<PresetPreview|null>(null),[results,setResults]=useState<PresetResult[]|null>(null),[confirmed,setConfirmed]=useState(false);
  const [error,setError]=useState<string|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
  const source=videos.find(video=>video.video_id===sourceVideoId),preset=presets.find(item=>item.preset_id===presetId),version=preset?.versions.find(item=>item.version_id===versionId);
  const canWrite=session.can('review.write');
  const locked=disabled||Boolean(busy)||!canWrite;
  useEffect(()=>{const controller=new AbortController();void Promise.all([reviewApi.videos(controller.signal),rulePresetsApi.list(controller.signal)]).then(([library,list])=>{if(controller.signal.aborted)return;setVideos(library.videos);setPresets(list.presets);const record=library.videos.find(item=>item.video_id===sourceVideoId);setSlots(record?sourceSlots(record):[]);setSelected(record?[record.video_id]:[]);}).catch(cause=>{if(!controller.signal.aborted)setError(explainError(cause));});return()=>controller.abort();},[sourceVideoId]);
  function invalidate(){setPreview(null);setResults(null);setConfirmed(false);setMessage('');}
  async function action(label:string,run:()=>Promise<void>){setBusy(label);onBusyChange?.(true);setError(null);setMessage('');try{await run();}catch(cause){setError(explainError(cause));}finally{setBusy('');onBusyChange?.(false);}}
  async function refreshTargets(){const library=await reviewApi.videos();setVideos(library.videos);const refreshed=library.videos.find(video=>video.video_id===sourceVideoId);if(refreshed)setSlots(current=>sourceSlots(refreshed).map(slot=>({...slot,name:current.find(item=>item.source_zone_id===slot.source_zone_id)?.name??slot.name})));invalidate();setMessage('Target revisions refreshed. Map scopes and preview again.');}
  async function save(existing=false){if(!source)throw new Error('Choose a saved source recording.');if(!name.trim())throw new Error('Give this preset a name.');if(existing&&!preset)throw new Error('Choose a preset to save a new version.');const result=await rulePresetsApi.save({name:name.trim(),description,source_video_id:source.video_id,source_revision:source.revision,expected_revision:existing?preset!.revision:0,slots},existing?presetId:undefined);setPresets(current=>[result,...current.filter(item=>item.preset_id!==result.preset_id)]);setPresetId(result.preset_id);setVersionId(result.current_version_id);setMaps({});invalidate();setMessage(`Saved ${result.name}, version ${result.versions.length}. Source polygons were not copied.`);}
  async function buildPreview(){if(!preset||!version)throw new Error('Choose a preset version first.');const targets=mappedTargets(videos,selected,maps,version);setPreview(await rulePresetsApi.preview({preset_id:presetId,version_id:versionId,mode,targets}));setResults(null);setConfirmed(false);}
  async function apply(){if(!preview||!confirmed)return;const result=await rulePresetsApi.apply(preview.preview_id);setResults(result.results);setConfirmed(false);const applied=result.results.filter(row=>row.status==='applied'||row.status==='already_applied').map(row=>row.video_id);await onApplied?.(applied);const library=await reviewApi.videos();setVideos(library.videos);setMessage(`Updated ${applied.length} recording(s). Analysis was not started; review all per-recording results below.`);}
  return <section className="rp-panel" aria-label="Reusable rule presets"><div className="rv-section-title"><div><span className="rv-kicker">PORTABLE RULES / EXPLICIT ZONE MAPPING</span><h2>Reuse the rule. Keep each camera’s geometry.</h2></div></div><p className="rv-small">Presets are shared within this tenant. Every application pins a saved version and requires a preview. Existing analysis results keep their recorded configuration.</p>{error&&<div role="alert" className="rv-error">{error}</div>}{message&&<p role="status" className="rv-notice">{message}</p>}{disabled&&!busy&&<p className="rv-small">Save or discard footage edits and finish processing before using presets.</p>}
    <fieldset className="rv-fieldset" disabled={disabled||Boolean(busy)}><div className="rp-grid"><section className="rp-card"><span className="rv-kicker">01 / SAVE FROM THIS RECORDING</span><h3>{source?.title??'Select a recording'}</h3><button className="rv-button" onClick={()=>void action('Refreshing saved configuration',refreshTargets)}>Refresh saved source and targets</button><label>Preset name<input maxLength={120} value={name} onChange={event=>setName(event.target.value)}/></label><label>Preset description<textarea maxLength={1500} rows={2} value={description} onChange={event=>setDescription(event.target.value)}/></label><p className="rv-small">Name the logical roles of the source zones used by your saved rules. A target camera must map each role to one of its own zones.</p>{slots.map((slot,index)=><div className="rp-slot" key={slot.slot_id}><span>{source?.zones.find(zone=>zone.zone_id===slot.source_zone_id)?.name??slot.source_zone_id}</span><label>Logical scope {index+1}<input maxLength={80} value={slot.name} onChange={event=>setSlots(current=>current.map((row,i)=>i===index?{...row,name:event.target.value}:row))}/></label></div>)}<p className="rv-small">{source?.rules.length??0} saved rules · entry/dwell, class, threshold, cooldown and enabled state are retained.</p><div className="rv-row"><button className="rv-button" disabled={!canWrite||!source?.rules.length||!name.trim()||slots.some(slot=>!slot.name.trim())} onClick={()=>void action('Saving preset',()=>save())}>Save new preset</button><button className="rv-button" disabled={!canWrite||!preset||!source?.rules.length||!name.trim()||slots.some(slot=>!slot.name.trim())} onClick={()=>void action('Saving version',()=>save(true))}>Save new version of selected preset</button></div></section>
    <section className="rp-card"><span className="rv-kicker">02 / MAP TO TARGET RECORDINGS</span><label>Saved rule preset<select value={presetId} onChange={event=>{const next=presets.find(item=>item.preset_id===event.target.value);setPresetId(event.target.value);setVersionId(next?.current_version_id??'');setMaps({});invalidate();}}><option value="">Choose a preset</option>{presets.map(item=><option key={item.preset_id} value={item.preset_id}>{item.name}</option>)}</select></label>{preset&&<><p className="rv-small">{preset.description}</p><label>Preset version<select value={versionId} onChange={event=>{setVersionId(event.target.value);setMaps({});invalidate();}}>{[...preset.versions].reverse().map(item=><option key={item.version_id} value={item.version_id}>Version {item.number} · {item.rules.length} rules · {new Date(item.created_at).toLocaleString()}</option>)}</select></label></>}{version&&<><ul className="rp-rules">{version.rules.map(rule=><li key={rule.rule_id}>{rule.name} · {rule.event_type} · {rule.target_class} · {version.slots.find(slot=>slot.slot_id===rule.slot_id)?.name} · {rule.enabled?'enabled':'disabled'}{rule.event_type==='dwell'?` · ${rule.threshold_s}s dwell`:''} · {rule.cooldown_s}s cooldown</li>)}</ul><label>Application mode<select value={mode} onChange={event=>{setMode(event.target.value as 'append'|'replace');invalidate();}}><option value="append">Append — preserve existing rules</option><option value="replace">Replace all existing rules — keep zones</option></select></label><div className="rv-row"><span className="rv-small">{selected.length}/20 targets selected</span><button className="rv-button" onClick={()=>void action('Refreshing targets',refreshTargets)}>Refresh target revisions</button></div>{videos.map(video=><article className="rp-target" key={video.video_id}><label className="rp-target-toggle"><input type="checkbox" checked={selected.includes(video.video_id)} disabled={!selected.includes(video.video_id)&&selected.length>=20} onChange={event=>{setSelected(current=>event.target.checked?[...current,video.video_id]:current.filter(id=>id!==video.video_id));invalidate();}}/>{video.title} · r{video.revision} · {video.status}</label>{selected.includes(video.video_id)&&<div className="rp-mappings">{version.slots.map(slot=><label key={slot.slot_id}>{slot.name} → {video.title}<select value={maps[video.video_id]?.[slot.slot_id]??''} onChange={event=>{setMaps(current=>({...current,[video.video_id]:{...(current[video.video_id]??{}),[slot.slot_id]:event.target.value}}));invalidate();}}><option value="">Choose this camera’s zone</option>{video.zones.map(zone=><option key={zone.zone_id} value={zone.zone_id}>{zone.name}</option>)}</select></label>)}</div>}</article>)}<button className="rv-button rv-primary" disabled={!canWrite||!selected.length} onClick={()=>void action('Previewing mapped rules',buildPreview)}>Preview preset changes</button></>}</section></div></fieldset>
    {preview&&<section className="rp-preview"><span className="rv-kicker">03 / REVIEW THE EXACT CHANGE</span><h3>{preview.preset_name} · version {preview.version_number} · {preview.mode}</h3><p className="rv-small">Preview expires {new Date(preview.expires_at).toLocaleTimeString()}. A newer preset version will not change this preview. Target edits or new processing jobs require a fresh preview.</p>{preview.results.map(result=><article className="rp-result" key={result.video_id}><strong>{result.title??videos.find(video=>video.video_id===result.video_id)?.title??result.video_id}</strong><span>{presetPreviewSummary(result,preview.mode)}</span>{result.status==='ready'&&<details><summary>Inspect resulting rules</summary><ul className="rp-rules">{result.final_rules?.map(rule=><li key={rule.rule_id}>{rule.name} · {rule.event_type} · {rule.target_class} · zone {videos.find(video=>video.video_id===result.video_id)?.zones.find(zone=>zone.zone_id===rule.zone_id)?.name??rule.zone_id}{rule.event_type==='dwell'?` · ${rule.threshold_s}s dwell`:''} · {rule.cooldown_s}s cooldown · {rule.enabled?'enabled':'disabled'}</li>)}</ul></details>}</article>)}{!results&&<><label className="rp-confirm"><input type="checkbox" checked={confirmed} disabled={locked} onChange={event=>setConfirmed(event.target.checked)}/>{preview.mode==='replace'?'I reviewed the mapped rules and approve replacing all rules on ready targets. Their polygons stay unchanged.':'I reviewed the mapped rules and approve appending them to the ready targets.'}</label><button className="rv-button rv-primary" disabled={locked||!confirmed||!preview.results.some(result=>result.status==='ready')} onClick={()=>void action('Applying preset',apply)}>Apply reviewed preset</button></>}{results&&<div role="status"><h3>Application results</h3>{results.map(result=><div className="rp-result" key={result.video_id}><strong>{result.title??videos.find(video=>video.video_id===result.video_id)?.title??result.video_id}</strong><span>{result.status.replaceAll('_',' ')}{result.revision?` · revision ${result.revision}`:''}{result.message?` · ${result.message}`:''}</span></div>)}</div>}<p className="rv-small">{preview.note}</p></section>}{busy&&<p role="status" className="rv-small">{busy}…</p>}</section>;
}
